### ISSUE TITLE
Add Plex Support

### ISSUE THREAD

**Issue by make92** [denysvitali/sonos-web#24]
not sure how active this is still maintained but i was wondering if its planed to integrate the Plex plugin?

**Comment by denysvitali** [comment]
It isn't planned in the README, but I will make sure to add it as planned ASAP.

By the way, the project is still maintained, but unfortunately I don't have much time to dedicate to it

**Comment by denysvitali** [comment]
@make92 Can you try out the newest Plex features? You'll need to add your Plex Token and the Plex Hostname to your settings.json file.  
  
```
{
  "debug": true,
  "port": 8888,
  "plugins": {
    "sonos-web-plex": {
      "token": "YOUR TOKEN HERE",
      "hostname": "whatever.domain.plex.direct" 
     }
   }
}
```

**Comment by denysvitali** [comment]
Plex seems to be well integrated now. :+1: 

Feel free to reopen the issue if you think something needs to be improved :rocket:
