### ISSUE TITLE
Running with a host firewall

### ISSUE THREAD

**Issue by barrydegraaff** [denysvitali/sonos-web#25]
Great work on this project! Seems to be the only viable option on Fedora.

By default it does not work, (fails to start completely), because it is blocked by the firewall that is installed by default on fedora. When I run iptables --flush, it works.

Please note, that the problem is not port 8888, I can access that from the local machine. 

It seems that the firewall prevents 2 other ports to be opened for listening:
tcp6       0      0 :::38549                :::*                    LISTEN      3796/node           
tcp6       0      0 :::8888                 :::*                    LISTEN      3796/node           
udp        0      0 0.0.0.0:54821           0.0.0.0:*                           3796/node 

Aka the ones with 38549, 54821, they change on every start of the npm.

What would be the best way to work around this? Set fixed ports, also can it be mixed ip4/ipv6 related?

**Comment by denysvitali** [comment]
Hello @barrydegraaff,
thanks for opening the issue.

sonos-web requires only the port 8888 to be open to work properly, but the discovery of Sonos devices is made via SSDP, which uses multicast packets.
You may want to try and use one of [these rules](https://gist.github.com/juliojsb/00e3bb086fd4e0472dbe)

**Comment by barrydegraaff** [comment]
That did not seem to work, I dug a bit deeper and it seems there is no service definition for upnp/ssdp in firewalld. Also debugging firewalld is painful.

The solution seems to be:
firewall-cmd --set-default-zone=FedoraWorkstation
firewall-cmd --reload

That does open the ports:
  <port protocol="udp" port="1025-65535"/>
  <port protocol="tcp" port="1025-65535"/>
And that makes sonos-web just work.

**Comment by denysvitali** [comment]
Meh, I always hated firewalld, probably the iptables rule doesn't work because it is appended, and there is a rule that redirects the other requests to firewalld tables. Therefore, if you want to try it, use the last rule and change `-A` to `-I` (append vs prepend).  
It should work.

But if you found the solution by using the Fedora Workstation ruleset, go with it. Although opening all the 1025-65535 ports seems excessive to me

**Comment by barrydegraaff** [comment]
Yeah, it is a bit excessive, but it is pre-defined by the people who should know best.
