### ISSUE TITLE
Youtube plugin tip

### ISSUE THREAD

**Issue by Coriou** [denysvitali/sonos-web#28]
Hey, I was just browsing through your code because I'm currently setting up a little system at home to easily stream Youtube to my Sonos speakers. I wish I found this project before... 

Anyway, I got it working and I have a little tip for your plugin (sorry I don't have time to PR this) :

In most cases, you actually don't need to transcode the video. I thought so too at first and it's how I was doing it. But it turns out, Youtube serves (for most videos) a format that Sonos can read. Look in the formats sent by ytdl and you just need to pick the audio codec `aac` in the `mp4` container. You can use the URL to stream directly from Youtube with all the good stuff (most important to me was consistent seeking because the way you're doing it now doesn't allow for real seeking through the track).

I can maybe PR this later if you don't do it. Ideally, you'd fall-back on transcoding if the desired format wasn't served by Youtube. So far, in my very humble testing, I've only found 1 video that didn't work using this technique and that I had to transcode.

EDIT : Here's an example URL I got from ytdl that you can feed directly to Sonos ([link](https://r1---sn-cv0tb0xn-uanl.googlevideo.com/videoplayback?dur=252.377&expire=1535557725&ip=176.175.148.78&key=yt6&lmt=1532720467303935&id=o-AFsA8j2cKLinV23BY1mi3exjm1dNJzsYo45mjPVmOX8e&fvip=6&source=youtube&initcwndbps=672500&mm=31%2C29&mn=sn-cv0tb0xn-uanl%2Csn-25glen7e&ratebypass=yes&gir=yes&requiressl=yes&ei=_WuGW_rMGMaAxgLapIFg&ms=au%2Crdu&mt=1535535999&mv=m&itag=18&pl=20&mime=video%2Fmp4&c=WEB&pcm2cms=yes&clen=18874086&ipbits=0&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&signature=64CAF3801F4ECE31BBDB5A1AC3184FA15275DF5E.3F29BFD9E1CEC79F7DF8175B54A491FD0ED88C62))

**Comment by Vittel** [comment]
True,
You can actually play a downloaded original YouTube file directly on Sonos (from a local fileshare). 
So playing the steam shouldn't be a large hurdle

**Comment by denysvitali** [comment]
Uh, that's a great news! I'll update the code accordingly as soon as I'm near my Sonos sound system (aka when I'm home)

**Comment by denysvitali** [comment]
I took a look today, but wasn't able to play the URL provided by youtube-dl. I haven't found a way to play `.aac` files w/ Sonos. Apparently my Play:3 only plays MP3 from `http://` URIs.  
  
Check my feature/youtube-fix-28 branch

**Comment by Coriou** [comment]
I haven't worked on this project since this issue actually... My habit of working on a project, then just abandoning it... 

So, I checked my code (I could put it on Github as it's really not sensible, but I feel very uncomfortable because it's quite shit tbh) and here's what I remembered :

- You need to pick the audio format "aac" in the "mp4" container (getting this from ytdl, the pure JS version, I think the same version you're using)
- You need to make the url end with ".mp4" for Sonos to decode it correctly

Can you double check this, and if you're still having problems I'll try to clean and put my code online as a reference.

**Comment by denysvitali** [comment]
Wait a second. Do they seriously only consider the file extension? I thought they were using the `Content-Type` header field. WTF  
  
I'll try again by adding `.mp4` to the URL and report back

**Comment by denysvitali** [comment]
Yeah, 16375c8 fixed it. Thank you for your suggestions! Now I'm also able to seek the songs played on YT :rocket:

**Comment by Coriou** [comment]
Nice job !

**Comment by denysvitali** [comment]
Thank you again for your suggestions! I also fixed the Soundcloud problem, therefore we can now seek songs easily
