### ISSUE TITLE
Possible optimisation?

### ISSUE THREAD

**Issue by andyfitter** [denysvitali/sonos-web#29]
Hi Jimmy. Just saw this on another project and thought you might be interested. 

https://github.com/denysvitali/sonos-web/issues/28

**Comment by denysvitali** [comment]
What?

**Comment by andyfitter** [comment]
Sorry, posted to the wrong project. :-)

Couldn’t find how to delete it, so closed it instead.

**Comment by denysvitali** [comment]
Don't worry (:
