### ISSUE TITLE
dynamic Port ? Docker machine 

### ISSUE THREAD

**Issue by MaMaRo123** [denysvitali/sonos-web#33]
Hi,
I want to build a public docker machine from your github repo, because people who have a NAS system with docker support would appreciate this.
Would it be possible to set the port to environment variables?

greetings from Berlin, Germany

**Comment by denysvitali** [comment]
Sure thing! I'll be sure to add this feature in a future release!

**Comment by denysvitali** [comment]
`SONOS_WEB_PORT=1234 yarn start` works without any problem :+1:
