### ISSUE TITLE
Room selection

### ISSUE THREAD

**Issue by dennisfrank** [denysvitali/sonos-web#9]
Hi, thanks for this project! I can see a lot of possible uses for it.

On the top left, the “Selected room” is displayed. Is it possible to change the room?

**Comment by denysvitali** [comment]
Dear Dennis,
thanks for asking.

The "Selected room" is the same you set in the Sonos Controller app, if you set a different name (for example "TV Room") in the Sonos Controller app the change will almost immediately be reflected to the Web interface and the image changed properly ([based on this](https://github.com/denysvitali/sonos-web/blob/master/src/js/inc/uievents.js#L98)).
Some preconfigured images / room names includes the following:

- Bedroom
- Bathroom
- Dining room
- Hall
- Kitchen
- Living room
- Media Room
- Patio
- Playroom
- Pool
- TV Room

The images can be found [here](https://github.com/denysvitali/sonos-web/tree/master/src/img/hero)

If you want to test out how the images will look like you can go to "UI Debug" and then select one of the images from the dropdown. Please note that this part is intended just to see how the rooms will be displayed and it isn't a feature to change the Sonos Room name
